## Spring Datasource
spring:
  datasource:
    url: jdbc:mysql://0.0.0.0/schema?useSSL=false&serverTimezone=UTC
    username: user
    password: pw

## Context path
server:
  :servlet
    :context-path=/api/v1
